services:
  db:
    image: mariadb
    command: --max-allowed-packet=64MB
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
    healthcheck:
      test: mariadb matomo --user=matomo --password='${MYSQL_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 20s
      timeout: 10s
      start_period: 20s
      retries: 5

  matomo:
    image: matomo:latest
    restart: unless-stopped
    environment:
      PHP_MEMORY_LIMIT: 2048M
      MATOMO_DATABASE_HOST: db
      MATOMO_DATABASE_DBNAME: matomo
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - matomo:/var/www/html
    ports:
      - ${PORT}:80
    healthcheck:
      test: curl --fail -s http://localhost:80/matomo.php || exit 1
      interval: 20s
      timeout: 10s
      start_period: 10s
      retries: 5

  archive:
    build:
      context: .
      dockerfile: ./docker/archive/Dockerfile
    restart: unless-stopped
    depends_on:
      matomo:
        condition: service_healthy
    environment:
      MATOMO_DATABASE_HOST: db
      PHP_MEMORY_LIMIT: 2048M
      MATOMO_DATABASE_ADAPTER: mysql
      MATOMO_DATABASE_TABLES_PREFIX:
      MATOMO_DATABASE_USERNAME: matomo
      MATOMO_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      MATOMO_DATABASE_DBNAME: matomo
      EMAIL: ${EMAIL}
    volumes:
      - matomo:/app
    healthcheck:
      test: php -l /app/console || exit 1
      interval: 10s
      timeout: 10s
      start_period: 5s
      retries: 5

  adminer:
    image: adminer
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - ${ADMINER}:8080

  auto-backup:
    image: fradelg/mysql-cron-backup
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backup:/backup
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=matomo
      - MYSQL_PASS=${MYSQL_PASSWORD}
      - MAX_BACKUPS=60
      - INIT_BACKUP=0
      - CRON_TIME=0 3 * * *
      - GZIP_LEVEL=9

  backup:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backup:/backup
      - matomo:/matomo
    command: >
      sh -c  "set -ex &&
        export BACKUP_DIR=matomo_$$(date +'%Y-%m-%d_%H-%M-%S') &&
        cd /backup && mkdir $$BACKUP_DIR &&
        cp -r /matomo/config /backup/$$BACKUP_DIR/ &&
        mariadb-dump --host db --extended-insert --no-autocommit --quick --single-transaction -uroot -p${MYSQL_ROOT_PASSWORD} matomo | gzip -c > /backup/$$BACKUP_DIR/dump.sql.gz &&
        tar -czf $$BACKUP_DIR.tar.gz $$BACKUP_DIR &&
        rm -rf /backup/$$BACKUP_DIR"
    profiles:
      - cli

  restore:
    image: mariadb
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: matomo
      MYSQL_USER: matomo
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - backup:/backup
      - matomo:/matomo
    command: >
      sh -c  "set -ex &&
        export FILE_TO_RESTORE=${BACKUP_FILE_TO_RESTORE:-no_file_to_restore} &&
        test -f /backup/$$FILE_TO_RESTORE &&
        RESTORE_DIR=$$(mktemp -d) &&
        tar -xf /backup/$$FILE_TO_RESTORE -C $$RESTORE_DIR --strip-components=1 &&
        cp -r $$RESTORE_DIR/config/* /matomo/config/ &&
        gzip -dc $$RESTORE_DIR/dump.sql.gz | mariadb --host db -uroot -p${MYSQL_ROOT_PASSWORD} matomo"
    profiles:
      - cli

  sanitize:
    image: mariadb
    restart: "no"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c  "mariadb-check --host db -uroot -p${MYSQL_ROOT_PASSWORD} -o --auto-repair --flush matomo"
    profiles:
      - cli

volumes:
  db:
    name: ${VOLUME_DB}
    external: true

  matomo:
    name: ${VOLUME_MATOMO}
    external: true

  backup:
    name: ${VOLUME_BACKUP}
    external: true
